### PR TITLE
Refactored QCJob

### PR DESCRIPTION
**Pull request by charles-cowart**
Small refactoring of QCCmdGenerator.

### CODE REVIEW

**Comment by charles-cowart** [comment]
Although branch is named 'kraken2', this is a refactoring of QCJob. Specifically, it is a merging of QCCmdGenerator and QCHelper into QCJob itself. This was done to make the code more clear, and make it easier to add kraken2.

**Review by antgonza — COMMENTED** [review]
This looks great, thank you; just a question, does this code have test or not? If not, can you add?

**Comment by charles-cowart** [comment]
The coverage is only 79%, but I did use the existing unit-tests to test as I systematically refactored out the other two files. The output products are identical, so I can say yes, it has tests and was tested. I will make an effort to get the coverage up into the 90%+ area, however.

**Comment by antgonza** [comment]
Thank you for checking. My guess that the target 90% will be in another PR, correct? If yes, I'll merge this.

**Comment by charles-cowart** [comment]
@antgonza Yes I'll be working on that shortly.

**Pull request merged**
