### PR TITLE
Added success confirmation for child jobs in arrays

### PR DESCRIPTION
**Pull request by charles-cowart**
QCJob and FastQCJob now generate '.completed' completed files; one for
each job in the array that completes successfully. After the primary job
completes, the number of .completed files is counted and an Error is
raised if the number is less than expected.

### CODE REVIEW

**Comment by charles-cowart** [comment]
@antgonza @jdereus Thank you guys for your patience! It's ready for review! This solution is the most basic and not relying on -W or other switches. This allowed me to develop and test it quickly. I think we could iterate on this solution as circumstances permit. One upgrade would be to offer what child jobs actually failed.

**Comment by antgonza** [comment]
No comments, in the current code ... but it would be pretty awesome if it would be possible to return in the error all the job-ids (including the job array id) that failed; what do you think? Easy to add?

**Comment by antgonza** [comment]
@charles-cowart, friendly ping about this one! I'm waiting for """... would be possible to return in the error all the job-ids (including the job array id) that failed; what do you think? Easy to add?"""

**Comment by charles-cowart** [comment]
@antgonza Sure, I can add it w/unittests today.

**Comment by charles-cowart** [comment]
@antgonza Sorry it took a little longer than expected to get the unittests right. The output file format is JSON, for the ease exporting and importing it into a data-structure, and in keeping w/some of the other log and configuration files. It is ready for review.

**Pull request merged**
